version: "3.3"

services:
  qix-engine:
    image: qlikea/engine:12.139.0
    command: -S AcceptEULA=${ACCEPT_EULA}
    ports:
      - "9076:9076"
    volumes:
      - ./data:/data
  file-connectivity-service:
    build: .
    ports:
      - 3000:3000
