version: 2
jobs:
  build:
    working_directory: ~/core-file-connectivity-service
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: npm-dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install --quiet
      - run:
          name: Run ESLint
          command: npm run lint
      - run:
          name: Run Component Tests
          command: npm run test:component
      - save_cache:
          key: npm-dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - setup_remote_docker
      - run:
          name: Spin up docker-compose
          command: ACCEPT_EULA=yes docker-compose up -d
      - run:
          name: Start container and check health
          command: |
            CONTAINER_ID=$(docker ps -aqf "name=file-connectivity-service")
            echo "Container id is $CONTAINER_ID"

            set +e
            # Check that the service reaches status healthy within 60 seconds
            RETRIES=0

            while [[ "$STATUS" != "healthy" && $RETRIES -le 30 ]]; do
              STATUS=$(docker inspect -f '{{.State.Health.Status}}' "$CONTAINER_ID")
              echo "Service status is $STATUS"
              sleep 2
              RETRIES=$[$RETRIES+1]
            done

            if [ "$STATUS" != "healthy" ]; then
              echo "Service did not reach status healthy"
              exit 1
            fi
