version: 2
jobs:
  build:
    working_directory: ~/outhaul
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install --quiet
      - run:
          name: Run ESLint
          command: npm run lint
      - run:
          name: Run Component Tests
          command: npm run test:component
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: ./scripts/cci2-install-docker-client.sh 17.04.0-ce
      - run:
          name: Build docker image
          command: docker build -t qlikea/outhaul .
      - run:
          name: Start container and check health
          command: |
            CONTAINER_ID=$(docker run qlikea/outhaul -d -p 3000:3000)

            set +e
            # Check that Outhaul reaches status healthy within 60 seconds
            RETRIES=0
            while (( STATUS != "healthy" && RETRIES != 6 )); do
              STATUS=$(docker inspect -f '{{.State.Health.Status}}' "$CONTAINER_ID")
              echo "Outhaul status is $STATUS"
              sleep 10
              RETRIES=$((RETRIES + 1 ))
            done
            if [ STATUS != "healthy" ]; then
              echo "Outhaul service did not reach status healthy"
              exit 1
            fi

