version: "3.3"
services:

  file-connectivity-service:
    build: ../
    ports:
      - 3000:3000
    environment:
      - DROPBOX_CLIENT_ID
      - DROPBOX_CLIENT_SECRET
      - ONE_DRIVE_CLIENT_ID
      - ONE_DRIVE_CLIENT_SECRET
      - GOOGLE_DRIVE_CLIENT_ID
      - GOOGLE_DRIVE_CLIENT_SECRET

  qix-engine:
    image: qlikcore/engine:12.160.0
    command: -S AcceptEULA=${ACCEPT_EULA}
    ports:
      - 19076:9076
